version: '3.7'

services:
services:
  cassandra:
    image: cassandra:3.11.8
    volumes:
      - cassandra_volumne:/var/lib/cassandra

  postgres-db:
    image: postgres:12.2-alpine
    volumes:
      - db_volume:/var/lib/postgresql/data/
    env_file:
      - ./services/postgres/dev.env
    stop_grace_period: 10s
  
  jupyter:
    build:
      context: ./services/jupyter
      dockerfile: Dockerfile
    ports:
      - 8888:8888
    volumes:
      - ./notebooks:/home/jovyan/work
  
volumes:
  db_volume:
  cassandra_volumne: